### PR TITLE
Feature 21 multi tab support

### PR DESCRIPTION
**Pull request by sgratzl**
see #21 starting support for multi tab support
 a. via a popup window that can be used to move a element to an window
 b. via a tab syncer that synchronizes for now just the selections across multiple windows

### CODE REVIEW

**Comment by thinkh** [comment]
Result with multiple popup windows:

multi-tab-support

**Review by thinkh — COMMENTED** [review]
@sgratzl Could you please point to the example code where you are using this functionality?

**Comment by sgratzl** [comment]
there is none

**Comment by thinkh** [comment]
According to @sgratzl he had only a local example. So no documentation about how to use it at the moment.

**Pull request merged**
