### PR TITLE
Mccalluc/port tests

### PR DESCRIPTION
**Pull request by mccalluc**
@sgratzl : I would appreciate your feedback here. I've brought over the qunit tests from the other branch, and translating them one by one.
- Would you object to bringing over the Object.keys tests? As I think about it now, they work for me as something like a table of contents at the top of the file, and then down below I can look at the behavior of individual methods.
- Would it be ok merge back into master incrementally? Beyond a green checkmark, are there things that matter to you here?
- Some of the tests have failed, for reasons I've had trouble diagnosing: for instance:
```
Chrome 54.0.2840 (Mac OS X 10.11.6) Circle corner encountered a declaration exception FAILED
	RangeError: Maximum call stack size exceeded
	    at vec (tests.webpack.js:2576:13)
	    at vec (tests.webpack.js:2578:12)
	    at vec (tests.webpack.js:2578:12)
	    at vec (tests.webpack.js:2578:12)
	    at vec (tests.webpack.js:2578:12)
```
... except that tests.webpack.js looks like this to me:
```
//build registry
require('./phovea_registry.js');
/**
 * find all tests in the spec directory and load them
 */
var context = require.context('./tests', true, /\.test\.ts$/); //make sure you have your directory and regex test set correctly!
context.keys().forEach(context);
```
How would I find line 2578?

More broadly, having the tests in TS works, but there are issues which we should acknowledge and try to mitigate.
- Because of the compilation + webpack + tslint time, the cycle between writing a test, seeing a failure, and correcting it is much slower now than when I was working in JS.
- I need to figure out how to get debugging to work.
- I need to figure out how to get DOM fixtures to work.
- Karma is a test runner... I think I could still be using QUnit syntax (`npm install -g karma-qunit`): Is this something folks have strong opinions about?

### CODE REVIEW

**Comment by sgratzl** [comment]
> Because of the compilation + webpack + tslint time,

why does `npm run test:watch` not work?

> I need to figure out how to get debugging to work.

there is a debug button in the chrome window top right

> Karma is a test runner... I think I could still be using QUnit syntax (npm install -g karma-qunit): Is this something folks have strong opinions about?

why adding another syntax, http://jasmine.github.io/ provides everything you need?

**Comment by sgratzl** [comment]
> I need to figure out how to get DOM fixtures to work.

we could give https://github.com/bessdsv/karma-jasmine-jquery a try.

**Comment by sgratzl** [comment]
> Would you object to bringing over the Object.keys tests? As I think about it now, they work for me as something like a table of contents at the top of the file, and then down below I can look at the behavior of individual methods.

at most just the public TypeScript fields. Howerver, especially in classes, Typescript compiles certain fields to public ones, too, despict that they should be private/protected. I don't wanna check for those fields, since they should be considered private/protected and not part of the public api. i.e. I can change them as I like as long as the Typescript public api doesn't change.

**Comment by mccalluc** [comment]
@sgratzl: Thanks! Since there have been changes in master, I'm going to merge that into this. Would it then be ok to merge this into master? The `.todo` files are a lot of clutter, but I think it's easier to have all the placeholders here, rather than having to continually reference the older branch.

**Comment by sgratzl** [comment]
you could think of removing all the todo files that doesn't contain any information,  i.e. just a placeholder for a unit test to write. Not yet ported files are fine of course

**Comment by mccalluc** [comment]
Ok, I'll remove the .todo files that are really empty, merge to master, and then rebranch to continue with this. Thanks.

**Pull request merged**
