### PR TITLE
Feature 24 version expansion

### PR DESCRIPTION
**Pull request by sgratzl**
see #24

### CODE REVIEW

**Comment by thinkh** [comment]
I don't understand the Travis error:

```
Firefox 31.0.0 (Linux 0.0.0)  version FAILED

	Expected '0.0.1-20161023-74657' to equal '__VERSION__'.

	@tests.webpack.js:5923:29

Firefox 31.0.0 (Linux 0.0.0): Executed 25 of 55 (1 FAILED) (0 secs / 0.008 secs)
```

@sgratzl Can you please fix or explain?

**Comment by sgratzl** [comment]
There is a magic constant called `__VERSION__` that will be expanded with the current version during build time. However, that wasn't the case, see #24. If fixed it but now the test fails that still checks for the old wrong behavior.

**Comment by thinkh** [comment]
Ok, thanks for explanation. Can you please commit the adapted test that travis is happy again?

**Comment by sgratzl** [comment]
> Can you please commit the adapted test that travis is happy again?

should I fix or remove the test? From my point of view, there is no need to test if the exposed version constant is X.

**Comment by thinkh** [comment]
How about modifying the test, so that it passes the following points:
- If the constant is defined (but not the value itself)
- That the version number follows the semantic version schema (01.00.05)

**Comment by sgratzl** [comment]
done

**Pull request merged**
