### PR TITLE
geom tests

### PR DESCRIPTION
**Pull request by mccalluc**
Translating geom tests. (Just Circle, really.)

@sgratzl: Does this look ok? The geometry makes sense, but I could use some help understanding the motivations... What is a basic tool which would make use of this code?

### CODE REVIEW

**Comment by sgratzl** [comment]
> What is a basic tool which would make use of this code?

e.g., https://github.com/phovea/phovea_d3/blob/master/src/link.ts -

I wrote the modules mainly for visual linking

**Comment by mccalluc** [comment]
@thinkh: Would you like to review this? There are some places where the behavior doesn't seem quite right, but I don't think I want to get into fixing the actual source code right now.

**Comment by thinkh** [comment]
All test are passing and it looks fine so far.
@mccalluc Will you fix the to dos in a new branch/PR?

**Comment by mccalluc** [comment]
@thinkh : Before we start changing behavior, even in good ways, I'd want to be more confident that nothing depends on the old behavior... but I'm not sure how to get there.

So I think I'll merge this just to make incremental progress.

**Pull request merged**
